## RabbitMQ Configuration
loopback_users.guest = false
listeners.tcp.default = 5672
management.listener.port = 15672
management.listener.ssl = false
default_vhost = community_finance
default_user = cfrabbit
default_pass = rabbitpass123
default_permissions.configure = .*
default_permissions.read = .*
default_permissions.write = .*
vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 2GB
